services:
  - type: web
    name: ocr-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
  - type: static_site
    name: ocr-frontend
    env: static
    buildCommand: "echo 'static site - no build'"
    staticPublishPath: frontend
    plan: free
